### ISSUE TITLE
Only full-time and part-time employees are visible on the homepage

### ISSUE THREAD

**Issue by RuchikaByte** [fossunited/fossunited#297]
### Issue description

The home page of FOSS United shows only full-time and part-time employees. IMO, we should feature active volunteers, as suggested by Kailash. This list also omits interns and board members. Instead of keeping the list big, we can highlight the active volunteers.

![Screenshot 2024-05-07 at 11 36 37 AM](https://github.com/fossunited/fossunited/assets/142503804/bceb0b0a-ff43-4a88-b7ef-482a7b6a5035)

**Comment by RiyaMathew-11** [comment]
We got a feedback earlier that board neednt be featured on the homepage and only employees should be - hence logic was written based on that. 

Will fix this in the next PR.

**Comment by rahulporuri** [comment]
> Will fix this in the next PR.

If fixing it involves the FOSS United tech team manually updating the list, i'm afraid that's sub-optimal because there is a high chance of the list being out-of-date.

We already have the list of volunteers for each city chapter in the city page. Is it possible in frappe to merge these lists for all cities and show them in a single location e.g. the Team page instead of the landing page?

That way, the FOSS United team is responsible for ensuring that the org team is up-to-date and the city chapters will be responsible for ensuring that their lists are up-to-date.

What do you think  @RiyaMathew-11 @RuchikaByte ?

**Comment by RiyaMathew-11** [comment]
No, it isn't a manual updation in code everytime - the lists can be updated in the desk itself. We have a specific team doctype. where we can add and delete and edit info of members.

Here in question for this bug, the logic was written in such a way that the members of the board were not made visible in the homepage. We need to alter that logic, which should be made in code, and hence needs to be put as a PR.

> Is it possible in frappe to merge these lists for all cities and show them in a single location

The city-volunteers are actually featured in their respective [community profile pages](https://fossunited.org/bengaluru). I think featuring all our volunteers in the landing page would be lengthy, as the number would easily range from 50+. 

However, I am planning on writing a page featuring our active and previous volunteers at the org. More of like a **community spotlight**. Thoughts @rahulporuri ?
