### ISSUE TITLE
[FEATURE] Migrate Job board to the new website

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#313]
### Feature description

The [job board](https://archive.fossunited.org/jobs) hasn't been migrated to the new website. We definitely want to maintain a job board so we should add it to the new website

### Use case

As an ecosystem enabler, FOSS United should attempt to bridge FOSS developers to companies in need of people with FOSS skill sets. This need still exists and a FOSS jobs board solves the problem.

### Alternatives considered

One of the problems with the earlier Jobs board was the lack of regular updates. We should consider alternative processes that can capture community submissions along with jobs submissions by the employers directly.

**Comment by rahulporuri** [comment]
@Mangeshrex are there any updates on this issue? I'm adding this issue to the Todo list for this month. We got two job postings on the Jobs channel on Telegram, which I would prefer having on the Jobs board instead of on Telegram.

**Comment by mngshm** [comment]
Updates: 

- I won't be doing a draft PR for this feature as there isn't much code going in other than some HTML, CSS and Frappe Scripts. 
- Completing this on the Desk Interface itself
- Wasn't able to work on this because of the [logout issue](https://github.com/fossunited/fossunited/issues/350#issuecomment-2173016801), have found a work around of working from Chromium as this only happens on Firefox.

@rahulporuri

**Comment by mngshm** [comment]
Update: 

Migrated the job board, and it is now available at https://fossunited.org/jobs. Please report if you find any bugs 

Closing this issue

**Comment by rahulporuri** [comment]
@Mangeshrex the job board looks good but it isn't accessible from fossunited.org, from what i can see. I don't know if we want to open a separate issue for this or if we should just fix that in this issue
