### ISSUE TITLE
[BUG] Search option on events timeline does not work

### ISSUE THREAD

**Issue by ansharora28** [fossunited/fossunited#358]
### Describe the bug

The implementation of the search feature seems to be on the event name. However, since all the events are named FOSS meetup it doesn't really help.

![image](https://github.com/fossunited/fossunited/assets/89684245/ff0e3375-36cd-4560-8b1c-f7b78acb58ce)
![image](https://github.com/fossunited/fossunited/assets/89684245/59261a73-40bc-4442-81cd-aa92917669be)
![image](https://github.com/fossunited/fossunited/assets/89684245/6a224a75-a58d-4788-bdc8-c62cbf42078b)

### Environment

```markdown
- Device:
- OS:
- Browser:
```

**Comment by RiyaMathew-11** [comment]
@ansharora28 

- Filter by city and chapter-type etc., are feat-enhancements that are to be added later on. 

- Search by month does work, but it is dependent on how the month is rendered on the event cards. 

Eg: Jun instead of June - while `Jun` is typed, it renders the filtered cards based on search. 

![timeline-capture](https://github.com/fossunited/fossunited/assets/60656677/f16b1af1-bb7a-4127-b42f-ed76e8f2508a)


We can implement this better too as an enhancement. I've referenced it all in #361

**Comment by RiyaMathew-11** [comment]
@ansharora28 

- Filter by city, chapter-type etc are a feature enhancements that were planned to be added later on, once we could rewrite the page in Vue.

- The search by month does work, but it's heavily dependent on how the month is rendered in the event cards. 

For eg: Jun instead of June. While typing `J` `u` `n`, the search does come up with the filtered options pertaining to the query added. 


![timeline-capture](https://github.com/fossunited/fossunited/assets/60656677/ccdce3ea-6047-42c1-b5f7-9aba90d0f42f)


While these things can be made more effective, I have referenced it all in #361
