### ISSUE TITLE
Not able to unpublish the CFP form 

### ISSUE THREAD

**Issue by ad1992** [fossunited/fossunited#547]
### Describe the bug

The chapter lead should have the control to publish and unpublish forms as before but since the last few meetups it doesn't allow to unpublish the CFP from 
<img width="648" alt="Screenshot 2024-08-14 at 7 47 06 PM" src="https://github.com/user-attachments/assets/db3426dd-f0fb-41c0-aa9a-923a8fb8c436">

### Expected behavior

The chapter lead should have the control to publish and unpublish forms

**Comment by rahulporuri** [comment]
thank you for reporting the bug @ad1992 , we will immediately look into this.

**Comment by harshtandiya** [comment]
Not the expected workflow. I think this was solved with the usage of dashboard. 

This particular workflow is deprecated and should be removed.

**Comment by harshtandiya** [comment]
Not the expected workflow. I think this was solved with the usage of dashboard. 

This particular workflow is deprecated and should be removed.

**Comment by rahulporuri** [comment]
> Not the expected workflow. I think this was solved with the usage of dashboard.

Please point out what the recommended workflow is and how to accomplish the relevant tasks (publishing CFP/RSVP forms) in the new workflow.

> This particular workflow is deprecated and should be removed.

Do we have issues regarding the depracation/removal? It will be good to identify the deprecated workflow in the code, in the UI and set a deadline for removal.

**Comment by harshtandiya** [comment]
Deprecated workflows will be removed with #507 

The expected workflow: 

- Log in to https://fossunited.org
- Click on `Dashboard` or go to https://fossunited.org/dashboard
- Click on `My Chapters` tab in the sidebar or go to https://fossunited.org/dashboard/chapter. A user with `Chapter Lead` or `Chapter Team Member` role should be able to access this 
Scheduled events should show up in this page itself. Please find the event and click on it. Otherwise click on your respective chapter card and go to `Events` tab on sidebar. This should show all the events of the chapter.
- In the Event page, go to CFP tab, you should be able to see unpublish cfp form button in the `Web Form` tab.
