### ISSUE TITLE
FIX CI : Refactor tests as per latest frappe requirements 

### ISSUE THREAD

**Issue by harshtandiya** [fossunited/fossunited#658]
### Issue description

It seems like frappe has changed how tests are written/accessed in the framework. This is resulting in failed CI for this project.

To fix:

- Move all the tests inside the `/<app>/tests` directory along with the `__init__.py` file.

References:

- https://github.com/frappe/frappe/blob/cf0f0a6e5f657187f10fbc9215f17da8d5200453/frappe/tests/README.md
- https://github.com/frappe/frappe/tree/develop/frappe/tests

**Comment by blaggacao** [comment]
https://github.com/frappe/frappe/pull/28032 this should fix your CI, for the moment.

However, you also might consider using `bench run-parallel-tests` (generally the upstream CI tool) instead of `bench run-tests` (generally used on CLI) &mdash; hopefully both code paths will eventually merge.

PS: I'm not working at frappe, just took the initiative to improve testing. Sorry for the inconvenience. Let me know if there's any other breakage.


cc @RiyaMathew-11 @akhilnarang

**Comment by RiyaMathew-11** [comment]
Thank you so much @blaggacao - Trying this fix out.

**Comment by blaggacao** [comment]
I did it, I own it. Nothing to thank for :smile: &mdash; apologies for the inconvenience.

**Comment by RiyaMathew-11** [comment]
partially solved with #654 - the failing test cases now need to be updated
