### ISSUE TITLE
IndiaFOSS 2024 schedule page not working

### ISSUE THREAD

**Issue by RuchikaByte** [fossunited/fossunited#661]
### Describe the bug

IndiaFOSS 2024 schedule page at https://fossunited.org/events/indiafoss24/schedule is not working. When I try to access it, it shows an error 404.

### Screenshots

![Screenshot 2024-10-14 at 3 19 52 PM](https://github.com/user-attachments/assets/8a38c9ca-11aa-42c0-8057-ed1fa17ad522)

**Comment by rahulporuri** [comment]
@ansharora28 noted that the CFP page is also not working - https://fossunited.org/events/indiafoss24/cfp/all

**Comment by harshtandiya** [comment]
This was fixed. Very tiny issue which i overlooked when changing the routes logic.

Indiafoss is also a chapter, hence the chapter's route is `/c/indiafoss` hence the event route should have changed to `c/indiafoss/indiafoss24` but it did not change as it was marked as external event.

This broke the schedule and all cfp pages which were anticipating `/c/` in the route of the event

I changed the routes from the desk, and event changed the redirects, so that it works fine again.
