### ISSUE TITLE
[BUG] Unique check for event creation doesnt take chapter into consideration

### ISSUE THREAD

**Issue by gi-yt** [fossunited/fossunited#690]
### Describe the bug

When an event is created under a FOSS City Chapter (like /c/mumbai/nov24), only the **nov24** part is considered in the unique check logic, meaning that no 2 chapters can have the same slug.

### Expected behavior

Allow multiple city chapters to have same slug like /nov24

### To Reproduce

Create an event with the "Event Permalink" set to nov24

### Screenshots

![image](https://github.com/user-attachments/assets/ce3a3546-5e43-45c1-ad6d-5bef9becbf76)
In this case, the event permalink is same for mumbai (which I was trying to create), and BLR (which was already created)

### Environment

```markdown
- Device: Desktop
- OS: Debian
- Browser: Zen Browser (Firefox)
```

**Comment by rahulporuri** [comment]
@vasujain275 would you like to check this out?

@harshtandiya correct me if im wrong but https://github.com/fossunited/fossunited/blob/52d139c771752bac4aaa84930d30437fd2957edf/fossunited/chapters/doctype/foss_chapter_event/foss_chapter_event.py#L119 is the source of the issue

**Comment by vasujain275** [comment]
@rahulporuri Sure, I'll take a look into it

**Comment by harshtandiya** [comment]
@vasujain275 any update on this? we can pair program this if you want, let me know

**Comment by vasujain275** [comment]
@harshtandiya haven't been able to took into it yet, we can do it together. Is there any calendar link where I can schedule meet with you?

**Comment by harshtandiya** [comment]
@vasujain275 https://cal.com/harshtandiya/15min

**Comment by vasujain275** [comment]
@rahulporuri @harshtandiya 

https://github.com/fossunited/fossunited/blob/52d139c771752bac4aaa84930d30437fd2957edf/fossunited/chapters/doctype/foss_chapter_event/foss_chapter_event.py#L119-L136

If we remove the chapter field from Line 128, will it solve the issue? I am unable to reproduce this on my local setup so that I can try this fix?

**Comment by harshtandiya** [comment]
@vasujain275 I don't think that will be logically correct. 

I think the error here is because the `permalink` field has a `unique` flag set to 1. This was done way back when permalinks were supposed to be unique, but that is no longer the case, so I think we can set it to 0.

![image](https://github.com/user-attachments/assets/2b8b61b1-e6eb-40e1-82b9-3ac8ca4b4c9f)

Desk > Doctype List > FOSS Chapter Event > Permalink > Uncheck Unique


Ofcourse, tests for this would be nice if there are not already

**Comment by rahulporuri** [comment]
@harshtandiya @vasujain275 i disagree with the proposed solution - the `permalink` field is supposed to be like `oct`, `2024oct`, `10-2024` and we should still ensure uniqueness e.g. using `dec` next month means that `dec` as the permalink for an event in dec 2025 shouldn't be possible.

isn't that correct? i hope I'm not missing something obvious.

**Comment by harshtandiya** [comment]
@rahulporuri if it's set to unique, it will make it such that it's unique over all the events. That's the essential error that we are getting right now.

Event routes are basically: `<chapter route>/<event route>`

So if hyd has a permalink `2024/oct` and lucknow tries to have a meetup in same month and try to have `2024/oct` it will throw error because the permalink is not unique even if the routes are diff

**Comment by gi-yt** [comment]
I don't have much experience with frappe or platform, but maybe you could make it such that permalink is a value where the /c/CHAPTER is added as a prefix before being inserted into the DB so that the unique check works as is

**Comment by harshtandiya** [comment]
@gi-yt that's how it works right now. The `route` is what sets the routes for event, that's prefixed with the c/chapter. Permalink is supposed to be local to a chapter
